name: 'bdt_transformations'
version: '1.0.0'
config-version: 2

profile: 'bdt_transformations'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  bdt_transformations:
    bitrix:
      +materialized: table
    notion:
      +materialized: table
    bendito:
      +materialized: table
    public:
      +materialized: table 