bdt_transformations:
  outputs:
    dev:
      type: postgres
      host: "{{ env_var('DESTINATION_HOST') }}"
      user: "{{ env_var('DESTINATION_ROOT_USER') }}"
      password: "{{ env_var('DESTINATION_ROOT_PASSWORD') }}"
      port: 5432
      dbname: "{{ env_var('DESTINATION_DB_NAME') }}"
      threads: 4
      schema: "processed"
      keepalives_idle: 0
      connect_timeout: 10
      retries: 1
  target: dev 