version: 2
models:
- name: ntn_processed_universal_task_database
  config:
    materialized: ephemeral
    enabled: true
- name: ntn_universal_task_database
  config:
    materialized: incremental
    enabled: true
    post-hook:
    - grant select on notion.ntn_universal_task_database to bendito_metabase
    unique_key: page_id
- name: ntn_processed_bendito_blueprint
  config:
    materialized: ephemeral
    enabled: true
- name: ntn_bendito_blueprint
  config:
    materialized: incremental
    enabled: true
    post-hook:
    - grant select on notion.ntn_bendito_blueprint to bendito_metabase
    unique_key: page_id
