version: 2
models:
- name: bdt_processed_action_items
  config:
    materialized: view
    enabled: true
- name: bdt_curated_action_items
  config:
    materialized: table
    enabled: true
- name: bdt_processed_bendito_blueprint
  config:
    materialized: view
    enabled: true
- name: bdt_curated_bendito_blueprint
  config:
    materialized: table
    enabled: true
- name: bdt_processed_universal_task_database
  config:
    materialized: view
    enabled: true
- name: bdt_curated_universal_task_database
  config:
    materialized: table
    enabled: true
