version: 2
models:
- name: ntn_processed_bendito_blueprint
  config:
    materialized: view
    enabled: true
- name: ntn_bendito_blueprint
  config:
    materialized: incremental
    enabled: true
    post-hook:
    - grant select on notion.ntn_bendito_blueprint to bendito_metabase
    - create unique index if not exists idx_ntn_bendito_blueprint_page_id on notion.ntn_bendito_blueprint
      using btree (page_id)
    unique_key: page_id
- name: ntn_processed_universal_task_database
  config:
    materialized: view
    enabled: true
- name: ntn_universal_task_database
  config:
    materialized: incremental
    enabled: true
    post-hook:
    - grant select on notion.ntn_universal_task_database to bendito_metabase
    - create unique index if not exists idx_ntn_universal_task_database_page_id on
      notion.ntn_universal_task_database using btree (page_id)
    unique_key: page_id
