version: 2
models:
- name: action_items
  config:
    materialized: incremental
    enabled: false
    unique_key: page_id
- name: universal_task_database
  config:
    materialized: incremental
    enabled: true
    unique_key: page_id
- name: bendito_blueprint
  config:
    materialized: incremental
    enabled: true
    unique_key: page_id
- name: ntn_processed_action_items
  config:
    materialized: ephemeral
    enabled: false
- name: ntn_processed_bendito_blueprint
  config:
    materialized: ephemeral
    enabled: true
- name: ntn_processed_universal_task_database
  config:
    materialized: ephemeral
    enabled: true
