version: 2

sources:
  - name: notion
    description: "Raw data imported from Notion"
    schema: notion
    tables:
      - name: ntn_raw_universal_task_database
      - name: ntn_raw_action_items
      - name: ntn_raw_bendito_blueprint