version: 2
models:
- name: crm_company
  config:
    materialized: incremental
    enabled: true
    unique_key: id
- name: crm_contact
  config:
    materialized: incremental
    enabled: true
    unique_key: id
- name: crm_activity
  config:
    materialized: incremental
    enabled: true
    unique_key: id
- name: crm_enum_activitydirection
  config:
    materialized: incremental
    enabled: true
    unique_key: id
- name: crm_deal_recurring
  config:
    materialized: incremental
    enabled: false
    unique_key: id
- name: crm_enum_addresstype
  config:
    materialized: incremental
    enabled: false
    unique_key: id
- name: crm_company_userfield
  config:
    materialized: incremental
    enabled: true
    unique_key: id
- name: crm_deal_userfield
  config:
    materialized: incremental
    enabled: true
    unique_key: id
- name: crm_enum_activitynotifytype
  config:
    materialized: incremental
    enabled: true
    unique_key: id
- name: crm_currency
  config:
    materialized: incremental
    enabled: true
    unique_key: id
- name: crm_enum_ownertype
  config:
    materialized: incremental
    enabled: false
    unique_key: id
- name: deal_fields
  config:
    materialized: incremental
    enabled: true
    unique_key: id
- name: user_get
  config:
    materialized: incremental
    enabled: true
    unique_key: id
- name: crm_catalog
  config:
    materialized: incremental
    enabled: true
    unique_key: id
- name: crm_lead
  config:
    materialized: incremental
    enabled: true
    unique_key: id
- name: crm_dealcategory
  config:
    materialized: incremental
    enabled: true
    unique_key: id
- name: crm_status
  config:
    materialized: incremental
    enabled: true
    unique_key: id
- name: crm_deal
  config:
    materialized: incremental
    enabled: true
    unique_key: id
- name: crm_product
  config:
    materialized: incremental
    enabled: true
    unique_key: id
- name: crm_enum_activitypriority
  config:
    materialized: incremental
    enabled: true
    unique_key: id
- name: crm_contact_userfield
  config:
    materialized: incremental
    enabled: true
    unique_key: id
- name: crm_dealcategory_stage
  config:
    materialized: incremental
    enabled: true
    unique_key: id
- name: btx_processed_crm_company
  config:
    materialized: ephemeral
    enabled: true
- name: crm_company
  config:
    materialized: incremental
    enabled: true
    unique_key: id
- name: btx_processed_crm_contact
  config:
    materialized: ephemeral
    enabled: true
- name: crm_contact
  config:
    materialized: incremental
    enabled: true
    unique_key: id
- name: btx_processed_crm_activity
  config:
    materialized: ephemeral
    enabled: true
- name: crm_activity
  config:
    materialized: incremental
    enabled: true
    unique_key: id
- name: btx_processed_crm_enum_addresstype
  config:
    materialized: ephemeral
    enabled: false
- name: crm_enum_addresstype
  config:
    materialized: incremental
    enabled: false
    unique_key: id
- name: btx_processed_crm_enum_activitynotifytype
  config:
    materialized: ephemeral
    enabled: true
- name: crm_enum_activitynotifytype
  config:
    materialized: incremental
    enabled: true
    unique_key: id
- name: btx_processed_deal_fields
  config:
    materialized: ephemeral
    enabled: true
- name: deal_fields
  config:
    materialized: incremental
    enabled: true
    unique_key: id
- name: btx_processed_user_get
  config:
    materialized: ephemeral
    enabled: true
- name: user_get
  config:
    materialized: incremental
    enabled: true
    unique_key: id
- name: btx_processed_crm_enum_activitydirection
  config:
    materialized: ephemeral
    enabled: true
- name: crm_enum_activitydirection
  config:
    materialized: incremental
    enabled: true
    unique_key: id
- name: btx_processed_crm_deal_recurring
  config:
    materialized: ephemeral
    enabled: false
- name: crm_deal_recurring
  config:
    materialized: incremental
    enabled: false
    unique_key: id
- name: btx_processed_crm_catalog
  config:
    materialized: ephemeral
    enabled: true
- name: crm_catalog
  config:
    materialized: incremental
    enabled: true
    unique_key: id
- name: btx_processed_crm_lead
  config:
    materialized: ephemeral
    enabled: true
- name: crm_lead
  config:
    materialized: incremental
    enabled: true
    unique_key: id
- name: btx_processed_crm_currency
  config:
    materialized: ephemeral
    enabled: true
- name: crm_currency
  config:
    materialized: incremental
    enabled: true
    unique_key: id
- name: btx_processed_crm_enum_ownertype
  config:
    materialized: ephemeral
    enabled: false
- name: crm_enum_ownertype
  config:
    materialized: incremental
    enabled: false
    unique_key: id
- name: btx_processed_crm_deal_userfield
  config:
    materialized: ephemeral
    enabled: true
- name: crm_deal_userfield
  config:
    materialized: incremental
    enabled: true
    unique_key: id
- name: btx_processed_crm_company_userfield
  config:
    materialized: ephemeral
    enabled: true
- name: crm_company_userfield
  config:
    materialized: incremental
    enabled: true
    unique_key: id
- name: btx_processed_crm_deal
  config:
    materialized: ephemeral
    enabled: true
- name: crm_deal
  config:
    materialized: incremental
    enabled: true
    unique_key: id
- name: btx_processed_crm_dealcategory
  config:
    materialized: ephemeral
    enabled: true
- name: crm_dealcategory
  config:
    materialized: incremental
    enabled: true
    unique_key: id
- name: btx_processed_crm_status
  config:
    materialized: ephemeral
    enabled: true
- name: crm_status
  config:
    materialized: incremental
    enabled: true
    unique_key: id
- name: btx_processed_crm_dealcategory_stage
  config:
    materialized: ephemeral
    enabled: true
- name: crm_dealcategory_stage
  config:
    materialized: incremental
    enabled: true
    unique_key: id
- name: btx_processed_crm_enum_activitypriority
  config:
    materialized: ephemeral
    enabled: true
- name: crm_enum_activitypriority
  config:
    materialized: incremental
    enabled: true
    unique_key: id
- name: btx_processed_crm_product
  config:
    materialized: ephemeral
    enabled: true
- name: crm_product
  config:
    materialized: incremental
    enabled: true
    unique_key: id
- name: btx_processed_crm_contact_userfield
  config:
    materialized: ephemeral
    enabled: true
- name: crm_contact_userfield
  config:
    materialized: incremental
    enabled: true
    unique_key: id
