version: 2
models:
- name: btx_processed_crm_company
  config:
    materialized: view
    enabled: true
- name: btx_crm_company
  config:
    materialized: incremental
    enabled: true
    post-hook:
    - grant select on bitrix.btx_crm_company to bendito_metabase
    - create index if not exists idx_btx_crm_company_id on bitrix.btx_crm_company
      using btree (id)
    unique_key: id
- name: btx_processed_crm_contact
  config:
    materialized: view
    enabled: true
- name: btx_crm_contact
  config:
    materialized: incremental
    enabled: true
    post-hook:
    - grant select on bitrix.btx_crm_contact to bendito_metabase
    - create index if not exists idx_btx_crm_contact_id on bitrix.btx_crm_contact
      using btree (id)
    unique_key: id
- name: btx_processed_crm_activity
  config:
    materialized: view
    enabled: true
- name: btx_crm_activity
  config:
    materialized: incremental
    enabled: true
    post-hook:
    - grant select on bitrix.btx_crm_activity to bendito_metabase
    - create index if not exists idx_btx_crm_activity_id on bitrix.btx_crm_activity
      using btree (id)
    unique_key: id
- name: btx_processed_crm_lead
  config:
    materialized: view
    enabled: true
- name: btx_crm_lead
  config:
    materialized: incremental
    enabled: true
    post-hook:
    - grant select on bitrix.btx_crm_lead to bendito_metabase
    - create index if not exists idx_btx_crm_lead_id on bitrix.btx_crm_lead using
      btree (id)
    unique_key: id
- name: btx_processed_crm_company_userfield
  config:
    materialized: view
    enabled: true
- name: btx_processed_crm_deal_userfield
  config:
    materialized: view
    enabled: true
- name: btx_processed_user
  config:
    materialized: view
    enabled: true
- name: btx_user
  config:
    materialized: incremental
    enabled: true
    post-hook:
    - grant select on bitrix.btx_user to bendito_metabase
    - create index if not exists idx_btx_user_id on bitrix.btx_user using btree (id)
    unique_key: id
- name: btx_processed_crm_deal
  config:
    materialized: view
    enabled: true
- name: btx_crm_deal
  config:
    materialized: incremental
    enabled: true
    post-hook:
    - grant select on bitrix.btx_crm_deal to bendito_metabase
    - create index if not exists idx_btx_crm_deal_id on bitrix.btx_crm_deal using
      btree (id)
    unique_key: id
- name: btx_processed_crm_dealcategory
  config:
    materialized: view
    enabled: true
- name: btx_processed_crm_contact_userfield
  config:
    materialized: view
    enabled: true
- name: btx_processed_crm_dealcategory_stage
  config:
    materialized: view
    enabled: true
- name: btx_processed_crm_product
  config:
    materialized: view
    enabled: true
- name: btx_crm_product
  config:
    materialized: incremental
    enabled: true
    post-hook:
    - grant select on bitrix.btx_crm_product to bendito_metabase
    - create index if not exists idx_btx_crm_product_id on bitrix.btx_crm_product
      using btree (id)
    unique_key: id
