version: 2

sources:
  - name: bitrix
    description: "Raw data imported from bitrix CRM"
    schema: bitrix
    tables:
      - name: btx_raw_crm_activity
      - name: btx_raw_crm_catalog
      - name: btx_raw_crm_company
      - name: btx_raw_crm_company_userfield
      - name: btx_raw_crm_contact
      - name: btx_raw_crm_contact_userfield
      - name: btx_raw_crm_currency
      - name: btx_raw_crm_deal
      - name: btx_raw_crm_deal_recurring
      - name: btx_raw_crm_deal_userfield
      - name: btx_raw_crm_dealcategory
      - name: btx_raw_crm_dealcategory_stage
      - name: btx_raw_crm_enum_activitydirection
      - name: btx_raw_crm_enum_activitynotifytype
      - name: btx_raw_crm_enum_activitypriority
      - name: btx_raw_crm_enum_addresstype
      - name: btx_raw_crm_enum_ownertype
      - name: btx_raw_crm_lead
      - name: btx_raw_crm_product
      - name: btx_raw_crm_status
      - name: btx_raw_user
      - name: btx_raw_deal_fields
