{{ config(
        materialized = 'table',
        unique_key = 'id',
        post_hook=[
            "ALTER TABLE {{ this }} ADD PRIMARY KEY (id)",
            "GRANT SELECT ON {{ this }} TO bendito_metabase",
            "CREATE INDEX IF NOT EXISTS idx_product_time_creation ON {{ this }} (time_creation)",
            "CREATE INDEX IF NOT EXISTS idx_product_time_modification ON {{ this }} (time_modification)",
            "CREATE INDEX IF NOT EXISTS idx_product_id_customer ON {{ this }} (id_customer)",
            "CREATE INDEX IF NOT EXISTS idx_product_family ON {{ this }} (family)",
            "CREATE INDEX IF NOT EXISTS idx_product_id_product ON {{ this }} (id_product)",
            "CREATE INDEX IF NOT EXISTS idx_product_creation_source ON {{ this }} (creation_source)",
        ],
    )}}
SELECT ("CONTENT"->>'id_customer')::integer AS id_customer,
("CONTENT"->>'id')::integer AS id,
("CONTENT"->>'description')::character varying AS description,
("CONTENT"->>'status')::integer AS status,
("CONTENT"->>'unit_measure')::integer AS unit_measure,
("CONTENT"->>'ncm')::integer AS ncm,
("CONTENT"->>'cest')::integer AS cest,
("CONTENT"->>'suplier_code')::character varying AS suplier_code,
("CONTENT"->>'customer_code')::character varying AS customer_code,
("CONTENT"->>'id_user_creation')::integer AS id_user_creation,
("CONTENT"->>'time_creation')::timestamp without time zone AS time_creation,
("CONTENT"->>'id_user_modification')::integer AS id_user_modification,
("CONTENT"->>'time_modification')::timestamp without time zone AS time_modification,
("CONTENT"->>'images')::text[] AS images,
("CONTENT"->>'family')::integer AS family,
("CONTENT"->>'id_product')::integer AS id_product,
("CONTENT"->>'integration_code')::character varying AS integration_code,
("CONTENT"->>'additional_information')::text AS additional_information,
("CONTENT"->>'b2b_sale')::boolean AS b2b_sale,
("CONTENT"->>'ean')::character varying AS ean,
("CONTENT"->>'stock')::numeric AS stock,
("CONTENT"->>'stock_reserved')::numeric AS stock_reserved,
("CONTENT"->>'stock_restrition')::boolean AS stock_restrition,
("CONTENT"->>'imported')::boolean AS imported,
("CONTENT"->>'resale')::boolean AS resale,
("CONTENT"->>'price')::numeric AS price,
("CONTENT"->>'id_matrix')::integer AS id_matrix,
("CONTENT"->>'anp_id')::integer AS anp_id,
("CONTENT"->>'portal_featured')::boolean AS portal_featured,
("CONTENT"->>'portal_discount')::boolean AS portal_discount,
("CONTENT"->>'use_multiplication_factor')::boolean AS use_multiplication_factor,
("CONTENT"->>'multiplication_factor_value')::numeric AS multiplication_factor_value,
("CONTENT"->>'icms_origem')::integer AS icms_origem,
("CONTENT"->>'icms_operacao')::integer AS icms_operacao,
("CONTENT"->>'cofins_operacao')::integer AS cofins_operacao,
("CONTENT"->>'pis_operacao')::integer AS pis_operacao,
("CONTENT"->>'subcategory')::integer AS subcategory,
("CONTENT"->>'numero_fci')::character varying AS numero_fci,
("CONTENT"->>'portal_included_date')::timestamp without time zone AS portal_included_date,
("CONTENT"->>'services')::integer AS services,
("CONTENT"->>'services_tax_value')::numeric AS services_tax_value,
("CONTENT"->>'services_taxation')::integer AS services_taxation,
("CONTENT"->>'configurable')::boolean AS configurable,
("CONTENT"->>'app_sale')::boolean AS app_sale,
("CONTENT"->>'creation_source')::integer AS creation_source
FROM {{source('bendito','bdt_raw_product')}}