version: 2

sources:
  - name: bendito
    description: "Raw data imported from bitrix CRM"
    schema: bendito
    tables:
      - name: bdt_raw_account_receivable
      - name: bdt_raw_anp
      - name: bdt_raw_approver
      - name: bdt_raw_business_unit
      - name: bdt_raw_buyer
      - name: bdt_raw_buyer_logs
      - name: bdt_raw_carrier
      - name: bdt_raw_cart
      - name: bdt_raw_cart_item
      - name: bdt_raw_cest
      - name: bdt_raw_cfop
      - name: bdt_raw_characteristic
      - name: bdt_raw_characteristic_value
      - name: bdt_raw_characteristic_value_dependency
      - name: bdt_raw_characteristic_value_dependency_rules
      - name: bdt_raw_characteristic_value_pricing
      - name: bdt_raw_characteristic_value_pricing_rules
      - name: bdt_raw_city
      - name: bdt_raw_classes
      - name: bdt_raw_classes_characteristic
      - name: bdt_raw_client
      - name: bdt_raw_cnae
      - name: bdt_raw_cofins_operacao
      - name: bdt_raw_collection
      - name: bdt_raw_collection_variation
      - name: bdt_raw_comercial_politics
      - name: bdt_raw_comercial_politics_rules
      - name: bdt_raw_comercial_politics_rules_criteria
      - name: bdt_raw_country
      - name: bdt_raw_custom_field
      - name: bdt_raw_custom_field_entity
      - name: bdt_raw_custom_group
      - name: bdt_raw_customer
      - name: bdt_raw_customer_buyer
      - name: bdt_raw_customer_contact
      - name: bdt_raw_customer_ncm
      - name: bdt_raw_customer_ncm_icms
      - name: bdt_raw_customer_ncm_st
      - name: bdt_raw_customer_nf_configuration
      - name: bdt_raw_customer_notes
      - name: bdt_raw_customer_plans
      - name: bdt_raw_customer_tasks
      - name: bdt_raw_customer_user
      - name: bdt_raw_deadline
      - name: bdt_raw_domain
      - name: bdt_raw_event_monitoring
      - name: bdt_raw_family
      - name: bdt_raw_feature
      - name: bdt_raw_feedback_question
      - name: bdt_raw_feedback_response
      - name: bdt_raw_goal
      - name: bdt_raw_goals_client_rules
      - name: bdt_raw_goals_invoice_rules
      - name: bdt_raw_goals_product_rules
      - name: bdt_raw_health_app
      - name: bdt_raw_icms
      - name: bdt_raw_icms_operacao
      - name: bdt_raw_icms_origem
      - name: bdt_raw_imported_nfe
      - name: bdt_raw_invoice
      - name: bdt_raw_invoice_approvers
      - name: bdt_raw_invoice_change
      - name: bdt_raw_invoice_issuance
      - name: bdt_raw_invoice_item
      - name: bdt_raw_invoice_item_characteristic
      - name: bdt_raw_invoice_status_log
      - name: bdt_raw_invoice_workflow
      - name: bdt_raw_ipi_operacao
      - name: bdt_raw_job
      - name: bdt_raw_lostreason
      - name: bdt_raw_mail_model
      - name: bdt_raw_market
      - name: bdt_raw_matrix
      - name: bdt_raw_ncm
      - name: bdt_raw_ncm_st
      - name: bdt_raw_payment_log
      - name: bdt_raw_payment_method
      - name: bdt_raw_payment_method_price_table
      - name: bdt_raw_payment_plan
      - name: bdt_raw_person
      - name: bdt_raw_person_address
      - name: bdt_raw_person_contact
      - name: bdt_raw_pis_operacao
      - name: bdt_raw_plans
      - name: bdt_raw_price_table
      - name: bdt_raw_product
      - name: bdt_raw_product_bom
      - name: bdt_raw_product_characteristic
      - name: bdt_raw_product_classes
      - name: bdt_raw_product_collection
      - name: bdt_raw_product_pricing
      - name: bdt_raw_product_sku
      - name: bdt_raw_product_sku_data
      - name: bdt_raw_product_warehouse
      - name: bdt_raw_profile
      - name: bdt_raw_profile_feature
      - name: bdt_raw_report_configuration
      - name: bdt_raw_route
      - name: bdt_raw_route_checkpoint
      - name: bdt_raw_route_execution
      - name: bdt_raw_route_workflow
      - name: bdt_raw_saldo_flex
      - name: bdt_raw_saldo_flex_historico
      - name: bdt_raw_sequence
      - name: bdt_raw_services
      - name: bdt_raw_services_taxation
      - name: bdt_raw_sku_pricing
      - name: bdt_raw_state
      - name: bdt_raw_subcategory
      - name: bdt_raw_team
      - name: bdt_raw_team_child
      - name: bdt_raw_token_info
      - name: bdt_raw_user
      - name: bdt_raw_user_configuration
      - name: bdt_raw_user_profile
      - name: bdt_raw_visit
      - name: bdt_raw_warehouse
      - name: bdt_raw_workflow