version: 2

sources:
  - name: bendito
    description: "Modelos curated do Bendito"
    schema: bendito
    tables:
      - name: bdt_account_receivable
      - name: bdt_anp
      - name: bdt_approver
      - name: bdt_business_unit
      - name: bdt_buyer
      - name: bdt_buyer_logs
      - name: bdt_carrier
      - name: bdt_cart
      - name: bdt_cart_item
      - name: bdt_cest
      - name: bdt_cfop
      - name: bdt_characteristic
      - name: bdt_characteristic_value
      - name: bdt_characteristic_value_dependency
      - name: bdt_characteristic_value_dependency_rules
      - name: bdt_characteristic_value_pricing
      - name: bdt_characteristic_value_pricing_rules
      - name: bdt_city
      - name: bdt_classes
      - name: bdt_classes_characteristic
      - name: bdt_client
      - name: bdt_cnae
      - name: bdt_cofins_operacao
      - name: bdt_collection
      - name: bdt_collection_variation
      - name: bdt_comercial_politics
      - name: bdt_comercial_politics_rules
      - name: bdt_comercial_politics_rules_criteria
      - name: bdt_country
      - name: bdt_custom_field
      - name: bdt_custom_field_entity
      - name: bdt_custom_group
      - name: bdt_customer
      - name: bdt_customer_buyer
      - name: bdt_customer_contact
      - name: bdt_customer_ncm
      - name: bdt_customer_ncm_icms
      - name: bdt_customer_ncm_st
      - name: bdt_customer_nf_configuration
      - name: bdt_customer_notes
      - name: bdt_customer_plans
      - name: bdt_customer_tasks
      - name: bdt_customer_user
      - name: bdt_deadline
      - name: bdt_domain
      - name: bdt_event_monitoring
      - name: bdt_family
      - name: bdt_feature
      - name: bdt_feedback_question
      - name: bdt_feedback_response
      - name: bdt_goals
      - name: bdt_goals_client_rules
      - name: bdt_goals_invoice_rules
      - name: bdt_goals_product_rules
      - name: bdt_health_app
      - name: bdt_icms
      - name: bdt_icms_operacao
      - name: bdt_icms_origem
      - name: bdt_imported_nfe
      - name: bdt_invoice
      - name: bdt_invoice_approvers
      - name: bdt_invoice_change
      - name: bdt_invoice_issuance
      - name: bdt_invoice_item
      - name: bdt_invoice_item_characteristic
      - name: bdt_invoice_status_log
      - name: bdt_invoice_workflow
      - name: bdt_ipi_operacao
      - name: bdt_job
      - name: bdt_lostreason
      - name: bdt_mail_model
      - name: bdt_market
      - name: bdt_matrix
      - name: bdt_ncm
      - name: bdt_ncm_st
      - name: bdt_payment_log
      - name: bdt_payment_method
      - name: bdt_payment_method_price_table
      - name: bdt_payment_plan
      - name: bdt_person
      - name: bdt_person_address
      - name: bdt_person_contact
      - name: bdt_pis_operacao
      - name: bdt_plans
      - name: bdt_price_table
      - name: bdt_product
      - name: bdt_product_bom
      - name: bdt_product_characteristic
      - name: bdt_product_classes
      - name: bdt_product_collection
      - name: bdt_product_pricing
      - name: bdt_product_sku
      - name: bdt_product_sku_data
      - name: bdt_product_warehouse
      - name: bdt_profile
      - name: bdt_profile_feature
      - name: bdt_report_configuration
      - name: bdt_route
      - name: bdt_route_checkpoint
      - name: bdt_route_execution
      - name: bdt_route_workflow
      - name: bdt_saldo_flex
      - name: bdt_saldo_flex_historico
      - name: bdt_sequence
      - name: bdt_services
      - name: bdt_services_taxation
      - name: bdt_sku_pricing
      - name: bdt_state
      - name: bdt_subcategory
      - name: bdt_team
      - name: bdt_team_child
      - name: bdt_token_info
      - name: bdt_user
      - name: bdt_user_configuration
      - name: bdt_user_profile
      - name: bdt_visit
      - name: bdt_warehouse
      - name: bdt_workflow
  - name: bitrix
    description: "Modelos curated do Bitrix"
    schema: bitrix
    tables:
      - name: btx_crm_deal
      - name: btx_crm_activity
      - name: btx_crm_company
      - name: btx_crm_contact
      - name: btx_crm_userfields
      - name: btx_user
      - name: btx_crm_product
      - name: btx_crm_lead
  - name: notion
    description: "Modelos curated do Notion"
    schema: notion
    tables:
      - name: ntn_universal_task_database
      - name: ntn_bendito_blueprint
      - name: ntn_users