version: 2

sources:
  - name: bendito
    description: "Modelos curated do Bendito"
    schema: bendito
    tables:
      - name: account_receivable
      - name: anp
      - name: approver
      - name: business_unit
      - name: buyer
      - name: buyer_logs
      - name: carrier
      - name: cart
      - name: cart_item
      - name: cest
      - name: cfop
      - name: characteristic
      - name: characteristic_value
      - name: characteristic_value_dependency
      - name: characteristic_value_dependency_rules
      - name: characteristic_value_pricing
      - name: characteristic_value_pricing_rules
      - name: city
      - name: classes
      - name: classes_characteristic
      - name: client
      - name: cnae
      - name: cofins_operacao
      - name: collection
      - name: collection_variation
      - name: comercial_politics
      - name: comercial_politics_rules
      - name: comercial_politics_rules_criteria
      - name: country
      - name: custom_field
      - name: custom_field_entity
      - name: custom_group
      - name: customer
      - name: customer_buyer
      - name: customer_contact
      - name: customer_ncm
      - name: customer_ncm_icms
      - name: customer_ncm_st
      - name: customer_nf_configuration
      - name: customer_notes
      - name: customer_plans
      - name: customer_tasks
      - name: customer_user
      - name: deadline
      - name: domain
      - name: event_monitoring
      - name: family
      - name: feature
      - name: feedback_question
      - name: feedback_response
      - name: goals
      - name: goals_client_rules
      - name: goals_invoice_rules
      - name: goals_product_rules
      - name: health_app
      - name: icms
      - name: icms_operacao
      - name: icms_origem
      - name: imported_nfe
      - name: invoice
      - name: invoice_approvers
      - name: invoice_change
      - name: invoice_issuance
      - name: invoice_item
      - name: invoice_item_characteristic
      - name: invoice_status_log
      - name: invoice_workflow
      - name: ipi_operacao
      - name: job
      - name: lostreason
      - name: mail_model
      - name: market
      - name: matrix
      - name: ncm
      - name: ncm_st
      - name: payment_log
      - name: payment_method
      - name: payment_method_price_table
      - name: payment_plan
      - name: person
      - name: person_address
      - name: person_contact
      - name: pis_operacao
      - name: plans
      - name: price_table
      - name: product
      - name: product_bom
      - name: product_characteristic
      - name: product_classes
      - name: product_collection
      - name: product_pricing
      - name: product_sku
      - name: product_sku_data
      - name: product_warehouse
      - name: profile
      - name: profile_feature
      - name: report_configuration
      - name: route
      - name: route_checkpoint
      - name: route_execution
      - name: route_workflow
      - name: saldo_flex
      - name: saldo_flex_historico
      - name: sequence
      - name: services
      - name: services_taxation
      - name: sku_pricing
      - name: state
      - name: subcategory
      - name: team
      - name: team_child
      - name: token_info
      - name: user
      - name: user_configuration
      - name: user_profile
      - name: visit
      - name: warehouse
      - name: workflow
  - name: bitrix
    description: "Modelos curated do Bitrix"
    schema: bitrix
    tables:
      - name: deal
      - name: activity
      - name: company
      - name: contact
      - name: userfields
      - name: user
      - name: product
      - name: lead
  - name: notion
    description: "Modelos curated do Notion"
    schema: notion
    tables:
      - name: universal_task_database
      - name: bendito_blueprint
      - name: users