version: 2

sources:
  - name: bendito
    description: "Modelos base do Bendito"
    schema: bendito
    tables:
      - name: bdt_curated_account_receivable
      - name: bdt_curated_anp
      - name: bdt_curated_approver
      - name: bdt_curated_business_unit
      - name: bdt_curated_buyer
      - name: bdt_curated_buyer_logs
      - name: bdt_curated_carrier
      - name: bdt_curated_cart
      - name: bdt_curated_cart_item
      - name: bdt_curated_cest
      - name: bdt_curated_cfop
      - name: bdt_curated_characteristic
      - name: bdt_curated_characteristic_value
      - name: bdt_curated_characteristic_value_dependency
      - name: bdt_curated_characteristic_value_dependency_rules
      - name: bdt_curated_characteristic_value_pricing
      - name: bdt_curated_characteristic_value_pricing_rules
      - name: bdt_curated_city
      - name: bdt_curated_classes
      - name: bdt_curated_classes_characteristic
      - name: bdt_curated_client
      - name: bdt_curated_cnae
      - name: bdt_curated_cofins_operacao
      - name: bdt_curated_collection
      - name: bdt_curated_collection_variation
      - name: bdt_curated_comercial_politics
      - name: bdt_curated_comercial_politics_rules
      - name: bdt_curated_comercial_politics_rules_criteria
      - name: bdt_curated_country
      - name: bdt_curated_custom_field
      - name: bdt_curated_custom_field_entity
      - name: bdt_curated_custom_group
      - name: bdt_curated_customer
      - name: bdt_curated_customer_buyer
      - name: bdt_curated_customer_contact
      - name: bdt_curated_customer_ncm
      - name: bdt_curated_customer_ncm_icms
      - name: bdt_curated_customer_ncm_st
      - name: bdt_curated_customer_nf_configuration
      - name: bdt_curated_customer_notes
      - name: bdt_curated_customer_plans
      - name: bdt_curated_customer_tasks
      - name: bdt_curated_customer_user
      - name: bdt_curated_deadline
      - name: bdt_curated_domain
      - name: bdt_curated_event_monitoring
      - name: bdt_curated_family
      - name: bdt_curated_feature
      - name: bdt_curated_feedback_question
      - name: bdt_curated_feedback_response
      - name: bdt_curated_goals
      - name: bdt_curated_goals_client_rules
      - name: bdt_curated_goals_invoice_rules
      - name: bdt_curated_goals_product_rules
      - name: bdt_curated_health_app
      - name: bdt_curated_icms
      - name: bdt_curated_icms_operacao
      - name: bdt_curated_icms_origem
      - name: bdt_curated_imported_nfe
      - name: bdt_curated_invoice
      - name: bdt_curated_invoice_approvers
      - name: bdt_curated_invoice_change
      - name: bdt_curated_invoice_issuance
      - name: bdt_curated_invoice_item
      - name: bdt_curated_invoice_item_characteristic
      - name: bdt_curated_invoice_status_log
      - name: bdt_curated_invoice_workflow
      - name: bdt_curated_ipi_operacao
      - name: bdt_curated_job
      - name: bdt_curated_lostreason
      - name: bdt_curated_mail_model
      - name: bdt_curated_market
      - name: bdt_curated_matrix
      - name: bdt_curated_ncm
      - name: bdt_curated_ncm_st
      - name: bdt_curated_payment_log
      - name: bdt_curated_payment_method
      - name: bdt_curated_payment_method_price_table
      - name: bdt_curated_payment_plan
      - name: bdt_curated_person
      - name: bdt_curated_person_address
      - name: bdt_curated_person_contact
      - name: bdt_curated_pis_operacao
      - name: bdt_curated_plans
      - name: bdt_curated_price_table
      - name: bdt_curated_product
      - name: bdt_curated_product_bom
      - name: bdt_curated_product_characteristic
      - name: bdt_curated_product_classes
      - name: bdt_curated_product_collection
      - name: bdt_curated_product_pricing
      - name: bdt_curated_product_sku
      - name: bdt_curated_product_sku_data
      - name: bdt_curated_product_warehouse
      - name: bdt_curated_profile
      - name: bdt_curated_profile_feature
      - name: bdt_curated_report_configuration
      - name: bdt_curated_route
      - name: bdt_curated_route_checkpoint
      - name: bdt_curated_route_execution
      - name: bdt_curated_route_workflow
      - name: bdt_curated_saldo_flex
      - name: bdt_curated_saldo_flex_historico
      - name: bdt_curated_sequence
      - name: bdt_curated_services
      - name: bdt_curated_services_taxation
      - name: bdt_curated_sku_pricing
      - name: bdt_curated_state
      - name: bdt_curated_subcategory
      - name: bdt_curated_team
      - name: bdt_curated_team_child
      - name: bdt_curated_token_info
      - name: bdt_curated_user
      - name: bdt_curated_user_configuration
      - name: bdt_curated_user_profile
      - name: bdt_curated_visit
      - name: bdt_curated_warehouse
      - name: bdt_curated_workflow
  - name: bitrix
    description: "Modelos base do Bitrix"
    schema: bitrix
    tables:
      - name: btx_curated_deal
      - name: btx_curated_activity
      - name: btx_curated_company
      - name: btx_curated_contact
      - name: btx_curated_userfields
      - name: btx_curated_user
      - name: btx_curated_product
      - name: btx_curated_lead